[tool.poetry]
name = "home-work-041224"
version = "0.1.0"
description = ""
authors = ["Alex-Stas <alexander.stashchuk@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
